# Custom HTTP headers
HTTP_HEADER_X_WORKER_NAME = "X-DISTRIBUTED-WORKER-NAME"
HTTP_HEADER_X_FILE_PATH = "X-DISTRIBUTED-FILE-PATH"

# URL paths
WORKER_PATH_NEW_FILE = "/new_file"
MASTER_PATH_WORKER_REGISTER = "/worker_register"
MASTER_PATH_GET_FILE = "/get_file"
MASTER_PATH_UPDATE_FILE_HASH = "/update_file_hash"
MASTER_PATH_HOME_STATUS = "/home_status"
